default: t

t:
    NO_DNA=1 anchor build
    cargo test --tests

tt:
    NO_DNA=1 anchor build
    ANCHOR_LITESVM_COLOR=1 cargo test --tests -- --nocapture --test-threads=1

# Each test emits target/md-reports/<slug>.md via the `Report` recorder; wipe
# that dir first (so a renamed test can't leave a stale section), then
# concatenate in sorted order behind a generated-file banner. Output is
# byte-stable across runs (deterministic keypairs), so it diffs clean.
#
# Assemble per-scenario reports into one doc, docs/testing/test-report.md.
test-md:
    #!/usr/bin/env bash
    set -euo pipefail
    NO_DNA=1 anchor build
    rm -rf target/md-reports
    cargo test --tests
    out=docs/testing/test-report.md
    mkdir -p docs/testing
    {
        echo '<!-- GENERATED by `just test-md`; do not edit by hand. -->'
        echo '# Escrow Test Report'
        echo
        echo 'One section per integration-test scenario, emitted by the `Report`'
        echo 'recorder and concatenated in sorted order. Regenerate with `just test-md`.'
        echo
        for f in $(ls target/md-reports/*.md | LC_ALL=C sort); do
            cat "$f"
            printf '\n---\n\n'
        done
    } > "$out"
    echo "wrote $out ($(ls target/md-reports/*.md | wc -l) scenarios)"
